---
name: CGI-Application-Plugin-Authentication
version: 0.15
author:
  - 'Cees Hek <ceeshek@gmail.com>'
abstract: Authentication framework for CGI::Application
license: perl
resources:
  license: http://dev.perl.org/licenses/
  repository: http://github.com/cees/cgi-application-plugin-authentication/tree
build_requires:
  Task::Weaken: 0
  Test::More: 0
  Test::Warn: 0.11
requires:
  Attribute::Handlers: 0
  CGI::Application: 4
  CGI::Cookie: 0
  Class::ISA: 0
  Digest::SHA1: 0
  MIME::Base64: 0
  Scalar::Util: 0
  UNIVERSAL::require: 0
  perl: 5.006
recommends:
  Apache::Htpasswd: v1.6.1
  CGI::Application::Plugin::Session: 0
  Color::Calc: 0.12
  Digest::MD5: 0
configure_requires:
  Module::Build: 0.35
provides:
  CGI::Application::Plugin::Authentication:
    file: lib/CGI/Application/Plugin/Authentication.pm
    version: 0.15
  CGI::Application::Plugin::Authentication::Driver:
    file: lib/CGI/Application/Plugin/Authentication/Driver.pm
  CGI::Application::Plugin::Authentication::Driver::Authen::Simple:
    file: lib/CGI/Application/Plugin/Authentication/Driver/Authen/Simple.pm
  CGI::Application::Plugin::Authentication::Driver::DBI:
    file: lib/CGI/Application/Plugin/Authentication/Driver/DBI.pm
  CGI::Application::Plugin::Authentication::Driver::Dummy:
    file: lib/CGI/Application/Plugin/Authentication/Driver/Dummy.pm
  CGI::Application::Plugin::Authentication::Driver::Filter::crypt:
    file: lib/CGI/Application/Plugin/Authentication/Driver/Filter/crypt.pm
  CGI::Application::Plugin::Authentication::Driver::Filter::lc:
    file: lib/CGI/Application/Plugin/Authentication/Driver/Filter/lc.pm
  CGI::Application::Plugin::Authentication::Driver::Filter::md5:
    file: lib/CGI/Application/Plugin/Authentication/Driver/Filter/md5.pm
  CGI::Application::Plugin::Authentication::Driver::Filter::sha1:
    file: lib/CGI/Application/Plugin/Authentication/Driver/Filter/sha1.pm
  CGI::Application::Plugin::Authentication::Driver::Filter::strip:
    file: lib/CGI/Application/Plugin/Authentication/Driver/Filter/strip.pm
  CGI::Application::Plugin::Authentication::Driver::Filter::uc:
    file: lib/CGI/Application/Plugin/Authentication/Driver/Filter/uc.pm
  CGI::Application::Plugin::Authentication::Driver::Generic:
    file: lib/CGI/Application/Plugin/Authentication/Driver/Generic.pm
  CGI::Application::Plugin::Authentication::Driver::HTPasswd:
    file: lib/CGI/Application/Plugin/Authentication/Driver/HTPasswd.pm
  CGI::Application::Plugin::Authentication::Store:
    file: lib/CGI/Application/Plugin/Authentication/Store.pm
  CGI::Application::Plugin::Authentication::Store::Cookie:
    file: lib/CGI/Application/Plugin/Authentication/Store/Cookie.pm
  CGI::Application::Plugin::Authentication::Store::Session:
    file: lib/CGI/Application/Plugin/Authentication/Store/Session.pm
generated_by: Module::Build version 0.35
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
keywords:
  - cgiapp
  - Titanium
  - authentication
